name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: check Sonar pre-conditions
        id: check_sonar
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONARCLOUD_ORGANIZATION }}
        run: test "${SONAR_ORGANIZATION}" -a "${SONAR_TOKEN}"
        shell: bash
      - name: Build with Sonar
        id: build_sonar
        if: matrix.java == '17' && steps.check_sonar.outcome == 'success' && !startsWith(github.head_ref, 'dependabot/')
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONARCLOUD_ORGANIZATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B clean test javadoc:jar site:site package verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=de.sephiroth-j:spring-security-ltpa2 -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.token=$SONAR_TOKEN
      - name: Build without Sonar
        if: steps.build_sonar.conclusion == 'skipped'
        run: mvn -B clean test package verify
